### ISSUE TITLE
User blocked the conversation with the bot

### ISSUE THREAD

**Issue by juancotrino** [ALERTua/msteamsapi#4]
I am using the example in your `README.md` file to test a webhook created with Workflows. I changed the `image url`, `EMAIL` and `NAME` strings to my corresponding company email and name, and a test image url. The workflow is failing and I am getting this error in the failure report:

```
Request to the Bot framework failed with error: '{\"error\":{\"code\":\"ConversationBlockedByUser\",\"message\":\"User blocked the conversation with the bot.\"}}'.
```

Any ideas of what is going on or what should I do to make this work?

Thanks in advance.

**Comment by ALERTua** [comment]
I just tested my example code from scratch:
```
from msteamsapi import TeamsWebhook, AdaptiveCard, Container, FactSet, ContainerStyle, TextWeight, TextSize

webhook = TeamsWebhook('https://prod-87.westeurope.logic.azure.com:443/workflows/blabla/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=blabla')

card = AdaptiveCard(title='card title', title_style=ContainerStyle.DEFAULT)
card.add_background(url="https://github.com/ALERTua/msteamsapi/raw/main/tests/background.png")

container = Container(style=ContainerStyle.DEFAULT)

card.mention('me@myemail.com', 'me', add_text_block=True)
mention_tag = card.mention('me@myemail.com', 'this dude')

container.add_image("https://github.com/ALERTua/msteamsapi/raw/main/tests/background.png", "image alt text")
container.add_text_block(
    'multiline\n\ntext\n\nmention 1: %s' % mention_tag,
    size=TextSize.DEFAULT, weight=TextWeight.DEFAULT, color="default"
)

factset = FactSet(('fact 1', 'fact 1 value'))
factset.add_facts(('fact 2', 'fact 2 value'), ('fact 3', 'fact 3 value'))
container.add_fact_set(factset)

card.add_container(container)

for i, url in enumerate(['https://google.com/', 'https://goo.gle']):
    card.add_url_button('url %s' % i, url)

webhook.add_cards(card)
webhook.send()
```

and everything works like a charm
![image](https://github.com/user-attachments/assets/24a24810-6e26-44e6-8367-c1876eeb86bf)
did you create a webhook for a public channel? a standard one?
![image](https://github.com/user-attachments/assets/6cecc144-26a8-4624-8810-c721f50a007c)

**Comment by juancotrino** [comment]
Ok. Got it working now. It was because I had the channel restrictions on like this: 
![image](https://github.com/user-attachments/assets/c9d3b90f-174c-488c-9263-3daad2ea36c0)
I thought the connector was the one posting the actual card, but it seems to be posting the card from my email, so I had to turn that setting off, or I assume giving specific posting permissions to my user would also work.

**Comment by damil69** [comment]
Здравствуйте. У меня такая же проблема: я навсегда заблокирован в FeedbackRandomGodBot, и бот отвечает только автоматическим сообщением. Я хотел бы пройти верификацию для разблокировки.

Мой Telegram: https://t.me/Iammilaad

Пожалуйста, подскажите, как получить ссылку на верификацию для моего аккаунта.
